---
title: "Bat Project"
author:"Darius Arasteh"

output: html_document
---

#Loading Libraries


```{r}
library(shiny)
library(shinydashboard)
library(tidyverse)
library(leaflet)
library(shiny)
library(shinydashboard)
library(tidyverse)

```


#Setting Up for Shiny App
```{r}
project_palette <- paletteer_d("calecopal::superbloom1")
capture <- read.csv("Data/capture_cleaned.csv") 
  
ui <- dashboardPage(
  dashboardHeader(title = "Capture Data Analysis"),
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("Analysis by Season", tabName = "season"),
      menuItem("Analysis by Sex", tabName = "sex"),
      menuItem("Analysis by Site", tabName = "cat"),
      menuItem("Morphological Scaling", tabName = "scaling")
    )
  ),
  
  dashboardBody(
    tabItems(
      # -------- SEASON TAB --------
      tabItem(tabName = "season",
        fluidRow(
          box(width = 4,
              selectInput("season_y",
                          "Group Variable",
                          choices = c("Forearm Length",
                                      "Ear Length",
                                      "Ageclass",
                                      "Region",
                                      "Reproductive Status",
                                      "Mass"))
          ),
          box(width = 8,
              plotOutput("season_plot"),
              verbatimTextOutput("season_text")
          )
        )
      ),
      
      # -------- SEX TAB --------
      tabItem(tabName = "sex",
        fluidRow(
          box(width = 4,
              selectInput("sex_y",
                          "Group Variable",
                          choices = c("Sex",
                                      "Ageclass",
                                      "Region",
                                      "Reproductivestatus"))
          ),
          box(width = 8,
              plotOutput("ear_plot"),
              verbatimTextOutput("ear_test")
          )
        )
      ),
      
      # -------- SCALING TAB --------
      tabItem(tabName = "scaling",
        fluidRow(
          box(width = 12,
              plotOutput("scaling_plot"),
              verbatimTextOutput("scaling_test")
          )
        )
      ),
      
      # -------- CATEGORICAL TAB --------
      tabItem(tabName = "cat",
        fluidRow(
          box(width = 4,
              selectInput("cat1",
                          "Variable 1",
                          choices = c("Sex",
                                      "Ageclass",
                                      "Region",
                                      "Reproductivestatus")),
              selectInput("cat2",
                          "Variable 2",
                          choices = c("Sex",
                                      "Ageclass",
                                      "Region",
                                      "Reproductivestatus"))
          ),
          box(width = 8,
              tableOutput("cat_table"),
              verbatimTextOutput("cat_test")
          )
        )
      )
    )
  )
)

server <- function(input, output) {
  
  # -------- FOREARM --------
  output$forearm_plot <- renderPlot({
    ggplot(capture,
           aes_string(x = input$forearm_x,
                      y = "Forearmlengthmm",
                      fill = input$forearm_x)) +
      scale_fill_manual(values=project_palette)+
      geom_boxplot() +
      theme_minimal() +
      labs(y = "Forearm Length (mm)")
  })
  
  output$forearm_test <- renderPrint({
    summary(aov(Forearmlengthmm ~
                capture[[input$forearm_x]],
                data = capture))
  })
  
  # -------- EAR --------
  output$ear_plot <- renderPlot({
    ggplot(capture,
           aes_string(x = input$ear_x,
                      y = "Earlengthmm",
                      fill = input$ear_x)) +
      scale_fill_manual(values=project_palette)+
      geom_boxplot() +
      theme_minimal() +
      labs(y = "Ear Length (mm)")
  })
  
  output$ear_test <- renderPrint({
    summary(aov(Earlengthmm ~
                capture[[input$ear_x]],
                data = capture))
  })
  
  # -------- SCALING --------
  output$scaling_plot <- renderPlot({
    ggplot(capture,
           aes(Forearmlengthmm,
               Earlengthmm)) +
      scale_fill_manual(values=project_palette)+
      geom_point() +
      geom_smooth(method = "lm",
                  se = FALSE,
                  color = "red") +
      theme_minimal()
  })
  
  output$scaling_test <- renderPrint({
    summary(lm(Earlengthmm ~ Forearmlengthmm,
               data = capture))
  })
  
  # -------- CATEGORICAL --------
  output$cat_table <- renderTable({
    table(capture[[input$cat1]],
          capture[[input$cat2]])
  })
  
  output$cat_test <- renderPrint({
    chisq.test(table(capture[[input$cat1]],
                     capture[[input$cat2]]))
  })
}

shinyApp(ui, server)
```


```{r}
library(shiny)
library(shinydashboard)
library(tidyverse)
library(paletteer)
library(leaflet)

project_palette <- paletteer_d("calecopal::superbloom1")

capture <- read.csv("Data/capture_cleaned.csv")

# Convert grouping variables to factors
capture$season <- as.factor(capture$season)
capture$sex <- as.factor(capture$sex)
capture$site <- as.factor(capture$site)

ui <- dashboardPage(
  
dashboardHeader(title = "Bat Capture Analysis"),

dashboardSidebar(
sidebarMenu(
menuItem("Season Analysis", tabName = "season"),
menuItem("Sex Analysis", tabName = "sex"),
menuItem("Region Analysis", tabName = "region"),
menuItem("Morphological Scaling", tabName = "scaling"),
menuItem("Capture Map", tabName = "map", icon = icon("map")))
),

dashboardBody(

  skin="lightblue",

tabItems(

# -------- SEASON TAB --------
tabItem(tabName = "season",
fluidRow(

box(width = 4,

selectInput("season_y",
"Variable",
choices = c("Forearm Length"="forearm",
"Ear Length"="ear",
"Mass"="mass"))

),

box(width = 8,

plotOutput("season_plot"),
verbatimTextOutput("season_text")

)

)
),

# -------- SEX TAB --------
tabItem(tabName = "sex",
fluidRow(

box(width = 4,

selectInput("sex_y",
"Variable",
choices = c("Forearm Length"="forearm",
"Ear Length"="ear",
"Mass"="mass"))

),

box(width = 8,

plotOutput("sex_plot"),
verbatimTextOutput("sex_text")

)

)
),

# -------- Region TAB --------
tabItem(tabName = "region",
fluidRow(

box(width = 4,

selectInput("region_y",
"Variable",
choices = c("Forearm Length"="forearm",
"Ear Length"="ear",
"Mass"="mass"))

),

box(width = 8,

plotOutput("region_plot"),
verbatimTextOutput("region_text")

)

)
),

# -------- SCALING TAB --------
tabItem(tabName = "scaling",
fluidRow(

box(width = 4,

selectInput("x_var",
"Body Measurement",
choices = c("Forearm Length" = "forearm",
"Ear Length" = "ear"))

),

box(width = 8,

plotOutput("scaling_plot"),
verbatimTextOutput("scaling_text")

)

)
),

# -------- LEAFLET MAP TAB --------
tabItem(tabName = "map",
  fluidRow(
    box(
      width = 12,
      leafletOutput("capture_map", height = 600)
    )
  )
)
)))
server <- function(input, output) {

# -------- SEASON PLOT --------
output$season_plot <- renderPlot({

ggplot(capture,
aes(x = season,
y = .data[[input$season_y]],
fill = season)) +

geom_boxplot() +

scale_fill_manual(values = project_palette) +

theme_minimal()

})

output$season_text <- renderPrint({

capture %>%
group_by(season) %>%
summarise(mean_value =
mean(.data[[input$season_y]], na.rm=TRUE))

})

# -------- SEX PLOT --------
output$sex_plot <- renderPlot({

ggplot(capture,
aes(x = sex,
y = .data[[input$sex_y]],
fill = sex)) +

geom_boxplot() +

scale_fill_manual(values = project_palette) +

theme_minimal()

})

output$sex_text <- renderPrint({

capture %>%
group_by(sex) %>%
summarise(mean_value =
mean(.data[[input$sex_y]], na.rm=TRUE))

})

# -------- Region PLOT --------
output$region_plot <- renderPlot({

ggplot(capture,
aes(x = region,
y = .data[[input$region_y]],
fill = region)) +

geom_boxplot() +

scale_fill_manual(values = project_palette) +

theme_minimal() +

theme(axis.text.x =
element_text(angle = 45, hjust = 1))

})

# -------- SCALING PLOT --------
output$scaling_plot <- renderPlot({

ggplot(capture,
aes(x = .data[[input$x_var]],
y = .data[[input$y_var]])) +

geom_point(color = project_palette[4], alpha = 0.7) +

geom_smooth(method="lm", color="black") +

theme_minimal()

})

output$scaling_text <- renderPrint({

model <- lm(capture[[input$y_var]] ~ capture[[input$x_var]])

summary(model)

})

# -------- LEAFLET MAP --------
output$capture_map <- renderLeaflet({

leaflet(data = capture) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    radius = 6,
    color = project_palette[3],
    fillOpacity = 0.8,
    stroke = FALSE,
    
    popup = ~paste0(
      "<b>Site:</b> ", site,
      "<br><b>Season:</b> ", season,
      "<br><b>Mass:</b> ", mass
    )
  )

})
}
shinyApp(ui, server)
```

